# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[tfenv]
src.git = "https://github.com/tfutils/tfenv"
fetch.github = "tfutils/tfenv"

[s5cmd]
src.git = "https://github.com/peak/s5cmd"
fetch.github = "peak/s5cmd"

[libcamera]
src.git = "https://github.com/raspberrypi/libcamera"
fetch.github = "raspberrypi/libcamera"
# src.manual = "e68e0f1ed2880ea26b5e317f94e2bbd5332e1598"
# src.manual = "2b1e1cd1ab12ae951fdb320968972c5c5f783e70"

[libcamera-apps]
src.git = "https://github.com/raspberrypi/libcamera-apps"
fetch.github = "raspberrypi/libcamera-apps"
# src.manual = "6bade0b112aca37fd9762d180203e376867ff09c"

[rtsp-simple-server]
# src.git = "https://github.com/aler9/rtsp-simple-server"
fetch.github = "aler9/rtsp-simple-server"
src.manual = "79562b15ab342bb34d29ffc3cae6a076ed51490a"

[moonraker]
src.git = "https://github.com/Arksine/moonraker"
fetch.github = "Arksine/moonraker"

[klipper]
src.git = "https://github.com/Klipper3d/klipper"
fetch.github = "Klipper3d/klipper"

[klipper-screen]
src.git = "https://github.com/jordanruthe/KlipperScreen"
fetch.github = "jordanruthe/KlipperScreen"

[klipper-led_effect]
src.git = "https://github.com/julianschill/klipper-led_effect"
fetch.github = "julianschill/klipper-led_effect"

[moonraker-telegram-bot]
src.git = "https://github.com/nlef/moonraker-telegram-bot"
src.branch = "development"
fetch.github = "nlef/moonraker-telegram-bot"

[mainsail]
src.github = "mainsail-crew/mainsail"
fetch.url = "https://github.com/mainsail-crew/mainsail/releases/download/$ver/mainsail.zip"

[mainsail-raw]
src.git = "https://github.com/mainsail-crew/mainsail"
src.branch = "develop"
fetch.github = "mainsail-crew/mainsail"

[cypress-aarch64]
src.manual = "10.10.0"
fetch.url = "https://cdn.cypress.io/desktop/$ver/linux-arm64/cypress.zip"

[transmissionic]
src.github = "6c65726f79/Transmissionic"
fetch.url = "https://github.com/6c65726f79/Transmissionic/releases/download/$ver/Transmissionic-webui-$ver.zip"

[rpi-linux]
src.git = "https://github.com/raspberrypi/linux"
fetch.github = "raspberrypi/linux"

[rpi-fw-nonfree]
src.git = "https://github.com/RPi-Distro/firmware-nonfree"
fetch.github = "RPi-Distro/firmware-nonfree"

[rpi-fw-bluez]
src.git = "https://github.com/RPi-Distro/bluez-firmware"
fetch.github = "RPi-Distro/bluez-firmware"

[rpi-fw]
src.git = "https://github.com/raspberrypi/firmware"
fetch.github = "raspberrypi/firmware"

[pam-reattach]
src.git = "https://github.com/fabianishere/pam_reattach"
fetch.github = "fabianishere/pam_reattach"

[otf2bdf]
src.git = "https://github.com/jirutka/otf2bdf"
fetch.github = "jirutka/otf2bdf"

[python-networkmanager]
src.pypi = "python-networkmanager"
fetch.pypi = "python-networkmanager"

[rel]
src.git = "https://github.com/bubbleboy14/registeredeventlistener"
fetch.github = "bubbleboy14/registeredeventlistener"

[wsaccel]
src.pypi = "wsaccel"
fetch.pypi = "wsaccel"

[zig]
fetch.github = "ziglang/zig"
src.manual = "d42a719e8f7ba31a9e18d6be9d58691b0b38c69a"
